[phases.setup]
nixpkgsArchive = "a370b2c86fa5c808a57323e3b63a4e022b15670b" # for bun v1.2
nixPkgs = ["nodejs_20", "bun"]
aptPkgs = ["build-essential", "python3"]

[phases.install]
dependsOn = ["setup"]
cmds = ["bun install"]

[phases.build]
dependsOn = ["install"]
cmds = ["bun run build:bot"]

[start]
runImage = "oven/bun:1.2.0"
cmd = "bun run start:bot"
