[phases.setup]
# https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/web/bun/default.nix
nixpkgsArchive = '7da4ed546d0579f8316ea521bd6e07e574bebd2c' # https://github.com/NixOS/nixpkgs/commit/7da4ed546d0579f8316ea521bd6e07e574bebd2c