[phases.setup]
# https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/web/bun/default.nix
nixpkgsArchive = 'fb713bf76ef45e1c673620be0d07a237c45b91da' # https://github.com/NixOS/nixpkgs/commit/fb713bf76ef45e1c673620be0d07a237c45b91da
