[phases.setup]
# https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/web/bun/default.nix
nixpkgsArchive = 'b5c86f0819fac69a6bb874249c512a0bdc4025e3' # https://github.com/NixOS/nixpkgs/commit/b5c86f0819fac69a6bb874249c512a0bdc4025e3
