[phases.setup]
nixPkgs = ["bun", "ffmpeg"]
providers = ["bun", "nodejs"]

[phases.install]
cmds = ["bun install", "node-gyp configure --module=/app/node_modules/@discordjs/opus/prebuild/node-v102-napi-v3-linux-x64-glibc-2.29/opus.node --module_name=opus --module_path=/app/node_modules/@discordjs/opus/prebuild/node-v102-napi-v3-linux-x64-glibc-2.29 --napi_version=9 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3"]
dependsOn = ["setup"]
