[phases.setup]
nixPkgs = ["nodejs_20", "bun"]
aptPkgs = ["build-essential", "python3"]

[phases.install]
dependsOn = ["setup"]
cmds = ["bun install"]

[phases.bodge]
dependsOn = ["install"]
cmds = ["bun run scripts/opus-bodge.ts"]

[phases.build]
dependsOn = ["bodge"]
cmds = ["bun run build:bot"]

[start]
runImage = "oven/bun:1.1"
cmd = "bun run start:bot"
