[phases.setup]
nixPkgs = ["bun", "nodejs_20"]
aptPkgs = [
  # @discordjs/opus
  "build-essential",
  "python3",
  # puppeteer
  "fonts-liberation",
  "libappindicator3-1",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libgbm1",
  "libgtk-3-0",
  "libnspr4",
  "libnss3",
  "libx11-xcb1",
  "libxcomposite1",
  "libxcursor1",
  "libxdamage1",
  "libxfixes3",
  "libxi6",
  "libxrandr2",
  "libxss1",
  "libxtst6",
  "xdg-utils",
]

[phases.install]
cmds = [
  "bun install",
  # @discordjs/opus bodge
  "cd node_modules/@discordjs/opus && node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/@discordjs/opus/prebuild/node-v115-napi-v3-linux-x64-glibc-2.29/opus.node --module_name=opus --module_path=/app/node_modules/@discordjs/opus/prebuild/node-v115-napi-v3-linux-x64-glibc-2.29 --napi_version=9 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3",
]
dependsOn = ["setup"]
