[phases.setup]
nixpkgsArchive = "8de37713e440b3eae10eadfbeac354e4b545092f" # for bun v1.1.42
nixPkgs = ["nodejs_20", "bun"]
aptPkgs = ["build-essential", "python3"]

[phases.install]
dependsOn = ["setup"]
cmds = ["bun install"]

[phases.build]
dependsOn = ["install"]
cmds = ["bun run build:bot"]

[start]
runImage = "oven/bun:1.1.42"
cmd = "bun run start:bot"
