[build]
builder = "NIXPACKS"
buildCommand = "turbo run build --filter=bot"
nixpacksConfigPath = "nixpacks.toml"

[build.nixpacksPlan.phases.install]
cmds = ["bun install"]
dependsOn = ["setup"]
providers = ["node"]

[deploy]
numReplicas = 1
restartPolicyMaxRetries = 100
restartPolicyType = "ON_FAILURE"
runtime = "UNSPECIFIED"
sleepApplication = false
startCommand = "cd apps/bot && bun run start"
