[build]
builder = "NIXPACKS"
buildCommand = "bun run bot:build"
nixpacksConfigPath = "nixpacks.toml"

[build.nixpacksPlan.phases.install]
cmds = ["bun install"]
dependsOn = ["setup"]
providers = ["node"]

[deploy]
numReplicas = 1
restartPolicyMaxRetries = 100
restartPolicyType = "ON_FAILURE"
runtime = "UNSPECIFIED"
sleepApplication = false
startCommand = "bun run bot:start"
