name: "💡 Feature request"
description: Suggest an idea for this project
labels: ["feature request"]

body:
  - type: textarea
    id: feature_description
    attributes:
      label: "Describe the feature"
      description: "A clear and concise description of what the feature is. Ex. I'm always frustrated when [...]"
      placeholder: "Describe the feature here"
    validations:
      required: true

  - type: textarea
    id: implementation_description
    attributes:
      label: "Describe how it could be implemented"
      description: "A clear and concise description of what you want to happen."
      placeholder: "How the feature could be implemented"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "Describe any alternatives"

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Additional information"
